# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [2]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [4]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [5]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [6]:
# Try to print or display it nicely.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [7]:
# Show the column names and their types.
df_food.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day',
       'vitamins', 'waffle_calories', 'weight'],
      dtype='str')

In [8]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
col_df = pd.DataFrame(df_food.columns, columns=['column_name'])
print(col_df)

                     column_name
0                            GPA
1                         Gender
2                      breakfast
3               calories_chicken
4                   calories_day
5                 calories_scone
6                         coffee
7                   comfort_food
8           comfort_food_reasons
9     comfort_food_reasons_coded
10                          cook
11  comfort_food_reasons_coded.1
12                       cuisine
13                  diet_current
14            diet_current_coded
15                         drink
16                eating_changes
17          eating_changes_coded
18         eating_changes_coded1
19                    eating_out
20                    employment
21                   ethnic_food
22                      exercise
23              father_education
24             father_profession
25                   fav_cuisine
26             fav_cuisine_coded
27                      fav_food
28                food_childhood
29                         fries
30                     fruit_day
31                   grade_level
32                    greek_food
33               healthy_feeling
34                  healthy_meal
35                    ideal_diet
36              ideal_diet_coded
37                        income
38                   indian_food
39                  italian_food
40                life_rewarding
41                marital_status
42           meals_dinner_friend
43              mother_education
44             mother_profession
45             nutritional_check
46                 on_off_campus
47                  parents_cook
48                  pay_meal_out
49                  persian_food
50        self_perception_weight
51                          soup
52                        sports
53                     thai_food
54             tortilla_calories
55               turkey_calories
56                   type_sports
57                   veggies_day
58                      vitamins
59               waffle_calories
60                        weight

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [9]:
# Remove ‘em.
list_of_col = ['calories_day', 'weight', 'Gender']
df_copy = df_food[list_of_col]
print(df_copy)

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [10]:
# Is there a second way to remove columns?
df_copy_2 = df_food[['calories_day', 'weight', 'Gender']]
print(df_copy_2)

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [11]:
# Count ‘em.

print(df_food.isna().sum().sum())
print(df_copy.isna().sum().sum())

149
21

In [ ]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [17]:
# Drop ‘em in-place.
df_copy=df_copy.dropna()

In [13]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
print(df_food.isnull().sum().sum())

149

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [22]:
# Fix that in-place.

df_copy['weight'] = pd.to_numeric(df_copy['weight'], errors='coerce')   
df_copy = df_copy.dropna()
df_copy.head()

   calories_day  weight  Gender
1           3.0   155.0       1
4           2.0   190.0       1
5           3.0   190.0       1
6           3.0   180.0       2
7           3.0   137.0       1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [23]:
# Savey save!
save_as = 'cleaned-data-file.csv'
df_copy.to_csv(save_as)

In [ ]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [45]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'

df_man = pd.read_csv(path,sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [29]:
# Count by hand. I’m dead serious.

df_man.shape

(28062, 18)

What are the columns and their types?

In [38]:
# Show the column names and their types.


df_man.dtypes

timestamp                          str
age                                str
industry                           str
title                              str
title_context                      str
salary                             str
additional_compensation        float64
currency                           str
other_currency                     str
salary_context                     str
country                            str
state                              str
city                               str
total_yoe                          str
field_yoe                          str
highest_education_completed        str
gender                             str
race                               str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [46]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed, gender, race
df_man.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed', 'gender', 'race']
df_man.dtypes

timestamp                          str
age                                str
industry                           str
title                              str
title_context                      str
salary                             str
additional_compensation        float64
currency                           str
other_currency                     str
salary_context                     str
country                            str
state                              str
city                               str
total_yoe                          str
field_yoe                          str
highest_education_completed        str
gender                             str
race                               str
dtype: object

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [47]:
# List the unique industries and a count of their instances.

df_man['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [109]:
# Filtery filter.
select_condition = df_man['industry'] == 'Computing or Tech'
df_man_copy = df_man[select_condition].copy()

Do a sanity check by counting.

In [110]:
# Sanity check count.

df_man_copy['industry'].value_counts()

industry
Computing or Tech    4699
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [112]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_man_copy['currency'].value_counts()
select_condition = df_man_copy['currency'] == 'USD'
df_man_copy = df_man_copy[select_condition].copy()
df_man_copy['currency'].value_counts()

currency
USD    3777
Name: count, dtype: int64

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [113]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_man_copy['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [114]:
# Replace them all in-place with 'US'.
list_of_top5 = ['United States','USA','US','U.S.','United States of America']
select_condition = df_man_copy['country'].isin(list_of_top5)
df_man_copy = df_man_copy[select_condition].copy()
df_man_copy['country'] = 'US'

Have a look at the count of each unique country again now.

In [91]:
# Count again.

df_man_copy['country'].value_counts()

country
US    3408
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [66]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

df_man_copy['salary'].agg(['min','mean','max'])

TypeError: Cannot perform reduction 'mean' with string dtype

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [115]:
# Fix it in-place.
df_man_copy['salary'] = pd.to_numeric(df_man_copy['salary'],errors='coerce')
df_man_copy=df_man_copy.dropna(subset=['salary'])
df_man_copy['salary'].value_counts()
df_man_copy['salary'].head()

8999       1.0
11900     55.0
15238      0.0
15885    240.0
18140     72.0
Name: salary, dtype: float64

In [101]:
df_man_copy.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8999,4/27/2021 17:02:03,35-44,Computing or Tech,Software Development Lead,NaN,1.0,130000.0,USD,NaN,NaN,US,Wisconsin,Madison,8 - 10 years,8 - 10 years,Master's degree,Man,White
11900,4/28/2021 6:41:31,45-54,Computing or Tech,Account Manager,NaN,55.0,12.0,USD,NaN,Base + commission,US,New Hampshire,Manchester,21 - 30 years,8 - 10 years,College degree,Woman,White
15238,4/28/2021 16:45:53,18-24,Computing or Tech,Product Marketer,NaN,0.0,0.0,USD,NaN,Start up without funding. Compensation is in s...,US,California,Santa Clara,1 year or less,1 year or less,College degree,Man,Asian or Asian American
15885,4/28/2021 17:22:37,25-34,Computing or Tech,Chief Data Scientist,NaN,240.0,100.0,USD,NaN,Additional compensation is expected value of o...,US,California,Oakland,5-7 years,5-7 years,PhD,Man,White
18140,4/28/2021 22:49:19,25-34,Computing or Tech,Technical Writer,NaN,72.0,0.0,USD,NaN,NaN,US,Washington,Silverdale,8 - 10 years,2 - 4 years,College degree,Woman,White

Let’s try that again.

In [116]:
# Try it again. Yeah!

df_man_copy['salary'].value_counts()
df_man_copy['salary'].agg(['min','mean','max'])

min     0.000000e+00
mean    1.279308e+05
max     2.600000e+06
Name: salary, dtype: float64

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [117]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_man_copy['timestamp'] = pd.to_datetime(df_man_copy['timestamp'])
years = [2021,2022]
select_condition = df_man_copy['timestamp'].dt.year.isin(years)
df_man_copy = df_man_copy[select_condition].copy()

In [118]:
df_man_copy.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8999,2021-04-27 17:02:03,35-44,Computing or Tech,Software Development Lead,NaN,1.0,130000.0,USD,NaN,NaN,US,Wisconsin,Madison,8 - 10 years,8 - 10 years,Master's degree,Man,White
11900,2021-04-28 06:41:31,45-54,Computing or Tech,Account Manager,NaN,55.0,12.0,USD,NaN,Base + commission,US,New Hampshire,Manchester,21 - 30 years,8 - 10 years,College degree,Woman,White
15238,2021-04-28 16:45:53,18-24,Computing or Tech,Product Marketer,NaN,0.0,0.0,USD,NaN,Start up without funding. Compensation is in s...,US,California,Santa Clara,1 year or less,1 year or less,College degree,Man,Asian or Asian American
15885,2021-04-28 17:22:37,25-34,Computing or Tech,Chief Data Scientist,NaN,240.0,100.0,USD,NaN,Additional compensation is expected value of o...,US,California,Oakland,5-7 years,5-7 years,PhD,Man,White
18140,2021-04-28 22:49:19,25-34,Computing or Tech,Technical Writer,NaN,72.0,0.0,USD,NaN,NaN,US,Washington,Silverdale,8 - 10 years,2 - 4 years,College degree,Woman,White

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)